ri
tunnel: 5e8ffd9c-2d6e-4669-b757-5ea478b77c03
credentials-file: /etc/cloudflared/5e8ffd9c-2d6e-4669-b757-5ea478b77c03.json
origincert: /etc/cloudflared/cert.pem
loglevel: debug

ingress:
  - hostname: links.abidc.dev
    service: http://linkstack:80
  - hostname: n8n.abidc.dev
    service: http://n8n:5678
  - hostname: chat.abidc.dev
    service: http://openwebui:8080
    originRequest:
      noTLSVerify: true
  - hostname: writing.abidc.dev
    service: http://ghost:2368
  - hostname: dashy.abidc.dev
    service: http://dashy:80
  - hostname: flowise.abidc.dev
    service: http://flowise:3000
  - hostname: docmost.abidc.dev
    service: http://docmost:3000
  - hostname: homarr.abidc.dev
    service: http://homarr:7575
  - hostname: portainer.abidc.dev
    service: http://portainer:9000
  - hostname: dockge.abidc.dev
    service: http://dockge:5001
  - hostname: mem0.abidc.dev
    service: http://mem0:8000
  - hostname: paperless.abidc.dev
    service: http://paperless:8000
  - hostname: homebox.abidc.dev
    service: http://homebox:7745
  - hostname: whiteboard.abidc.dev
    service: http://excalidraw:80
  - service: http_status:404
